AWSTemplateFormatVersion: 2010-09-09
Description: Sample New Relic AI Notifications Destination Template
Resources:
  Resource1:
    Type: 'NewRelic::Observability::AINotificationsDestination'
    Properties:
      Destination: >-
        destination: {name: "Email destination test", properties: {key: "email", value: "someone@somewhere.com"}, type: EMAIL}
Outputs:
  CustomResourceAttribute1:
    Value: !GetAtt  Resource1.Id
